- docs/adr/assets/ADR-003/examples/golang/go.mod
- scripts/docker/examples/python/assets/hello_world/requirements.txt
Amended the files below to fix security issues reported by the Dependbot
- modified:   docs/adr/assets/ADR-003/examples/golang/go.mod
- modified:   scripts/docker/examples/python/assets/hello_world/requirements.txt
---
> fix: issues reported by Dependbot

- infrastructure/modules/network-security-group/main.tf
- infrastructure/modules/network-security-group/variables.tf
- infrastructure/modules/shared-config/output.tf
- infrastructure/modules/subnet/variables.tf
- infrastructure/modules/vnet-peering/main.tf
- infrastructure/modules/vnet/output.tf
This PR adds support to the NSG and subnet modules for port ranges (plural) and subnet ranges (plural) in NSG rules. It's somewhat cumbersome to do because many Terraform functions fail when fed nulls, and variables do not behave in a truthy manner so nulls must be checked explicitly. XOR logic is required in validation to allow a range parameter (singular) or a ranges parameter (plural), but not neither, and not both.
This makes it easier to configure rules which are maintained and published by third parties (in this case GitHub Actions runner IPs) by simply dropping them in without having to painstakingly re-write them.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal …
> DTOS-3512-3514 Add support for port and address ranges to NSG rules in subnets

- infrastructure/modules/function-app/main.tf
- infrastructure/modules/function-app/output.tf
- infrastructure/modules/function-app/variables.tf
New module to allow creation of Azure Linux Function Apps
---
> feat: dtoss-4393 New Function App module - still requires PEP

- infrastructure/modules/azure-container-registry/main.tf
- infrastructure/modules/azure-sql-server/main.tf
- infrastructure/modules/function-app/main.tf
- infrastructure/modules/key-vault/main.tf
- infrastructure/modules/storage/main.tf
Update module references to latest versions.
---
> feat: Update module version refs

- infrastructure/modules/function-app/main.tf
- infrastructure/modules/function-app/rbac.tf
- infrastructure/modules/function-app/variables.tf
- infrastructure/modules/key-vault/output.tf
- infrastructure/modules/rbac-assignment/main.tf
Minor updates to fix additional security requirements.
---
> feat: dtoss 0000 function app security updates

- infrastructure/modules/function-app/rbac.tf
> feat: update Git module ref

- infrastructure/modules/sql-server/main.tf
- infrastructure/modules/sql-server/variables.tf
The Azure SQL module firewall rules need to be optional as they are not permitted to be set if public networking is disabled.
---
> feat: dtoss 0000 fix sql firewall rules

- infrastructure/modules/firewall/examples/main.tf
- infrastructure/modules/firewall/main.tf
- infrastructure/modules/firewall/outputs.tf
- infrastructure/modules/storage/rbac.tf
- infrastructure/modules/storage/variables.tf
Add RBAC to the storage account for the MI
---
> feat: dtoss 0000 add storage rbac

- infrastructure/modules/shared-config/output.tf
Add firewall name to config map.
---
> feat: DTOSS-3407 Add firewall config map name

- infrastructure/modules/public-ip/main.tf
- infrastructure/modules/public-ip/variables.tf
Updates to Firewall Templates - add missing Domain Name Label attribute.
---
> feat: dtoss 3407 azure firewall template updates

- infrastructure/modules/api-management/examples/main.tf
- infrastructure/modules/api-management/main.tf
- infrastructure/modules/api-management/output.tf
- infrastructure/modules/api-management/variables.tf
This pull request introduces a new Terraform module for managing Azure API Management resources. The module is designed to simplify the deployment and configuration of API Management services, including support for various configurations and features.
---
> Adding APIM module

- infrastructure/modules/firewall-rule-collection-group/variables.tf
- infrastructure/modules/route-table/variables.tf
Updates to Firewall and Routing modules
---
> feat: DTOSS-3407 Updates for network routing

- .gitignore
- infrastructure/modules/app-insights/main.tf
- infrastructure/modules/app-insights/output.tf
- infrastructure/modules/app-insights/variables.tf
- infrastructure/modules/baseline/base-rg.tf
- infrastructure/modules/baseline/outputs.tf
- infrastructure/modules/baseline/variables.tf
- infrastructure/modules/function-app/output.tf
- infrastructure/modules/log-analytics-workspace/main.tf
- infrastructure/modules/log-analytics-workspace/output.tf
- infrastructure/modules/log-analytics-workspace/variables.tf
- infrastructure/modules/private-link-scope/main.tf
- infrastructure/modules/private-link-scope/output.tf
- infrastructure/modules/private-link-scope/variables.tf
- infrastructure/modules/private-link-scoped-service/main.tf
- infrastructure/modules/private-link-scoped-service/output.tf
- infrastructure/modules/private-link-scoped-service/variables.tf
Migration (addition) of `tf-audit` modules from dtos-cohort-manager repo.
---
> feat: DTOSS-4810 centralise audit modules

- infrastructure/modules/shared-config/output.tf
Remove some naming tech debt arising from forked copies of the shared-config Terraform module
---
> fix: Resolve some naming tech debt

- infrastructure/modules/shared-config/output.tf
Add location code output to translate location name
---
> fix: Add location code output to translate location name

- infrastructure/modules/function-app-slots/main.tf
- infrastructure/modules/function-app-slots/variables.tf
> feat: DTOSS-5468 Create Azure Module for slots

- infrastructure/modules/key-vault/main.tf
- infrastructure/modules/key-vault/variables.tf
> fix: set Key Vault Public Access to default false

- infrastructure/modules/shared-config/output.tf
> fix: Fix App Insights names

- .azuredevops/templates/steps/tf_apply.yaml
To improve clarity now that multiple repos are being checked out, all repo checkouts will be made in the main pipeline YAML.
Improved developer comprehension.
---
> fix: move repo checkouts from templates to explicit in pipeline YAML

- .azuredevops/templates/steps/tf_apply.yaml
Fix to scope the PowerShell authentication context in Terraform Apply template to the correct target subscription.
Stops a warning (this Tenant has multiple subscriptions), and will be needed for Application Gateway Config module.
---
> fix: scope PowerShell auth to target subscription ID

- .github/workflows/stage-1-commit.yaml
- .github/workflows/stage-3-build-images.yaml
- scripts/reports/create-sbom-report.sh
- scripts/reports/scan-vulnerabilities.sh
This PR template the docker image creation pipeline process so it can be used by multiple projects across the DTOS project without the need to copy this script into each target repo. 
---
> Feat/dtoss 5411 setup GitHub ci for docker image creation and security scans

- .github/workflows/stage-1-commit.yaml
- .github/workflows/stage-3-build-images.yaml
- infrastructure/modules/route-table/providers.tf
Small fix to prevent a provider warning when using the route-table module to target an azurerm provider alias for a separate target subscription.
Tidy of `stage-3-build-images.yaml` for consistent bracing of variable names. Make one job's outputs more clear.
---
> fix: DTOSS-4810 fix provider warning in route-table module

- .azuredevops/templates/steps/tf_apply.yaml
- .azuredevops/templates/steps/tf_plan.yaml
- infrastructure/modules/virtual-desktop/main.tf
- infrastructure/modules/virtual-desktop/session-host.tf
- infrastructure/modules/virtual-desktop/variables.tf
- Amend Terraform pipeline steps templates so that Apply stage is optionally PowerShell, but defaults to AzureCLI.
- Improve parameterisation of Virtual Desktop module
This change clears the way for the Let's Encrypt Certificate Terraform module.
---
> fix: DTOSS-5711 terraform pipeline changes for cert automation

- infrastructure/modules/key-vault/main.tf
- infrastructure/modules/key-vault/variables.tf
- infrastructure/modules/lets-encrypt-certificate/data.tf
- infrastructure/modules/lets-encrypt-certificate/main.tf
- infrastructure/modules/lets-encrypt-certificate/output.tf
- infrastructure/modules/lets-encrypt-certificate/scripts/certbot.sh
- infrastructure/modules/lets-encrypt-certificate/variables.tf
- Automated Terraform module for requesting SSL certificates, renewing them, and storing them in Key Vault.
- Fix to the Key Vault Terraform module to allow RBAC authentication mode.
Let's Encrypt offers free browser-trusted SSL certificates with a validity of 3 months, provided DNS domain ownership can be authenticated. By automating the requesting of these certificates using the certbot tool with an Azure DNS authoriser plugin, and persisting the certbot state in a Storage Account the entire process can be wrapped in Terraform.
When the pipeline runs, any existing certificate with less than 30 days until expiry will be automatically renewed, stored in the specified Key Vaults, and resources which use this certificate will be updated.
- [Successful build of Dev …
> feat: DTOSS-5711 Let's Encrypt certificate module

- .github/workflows/stage-3-build-images.yaml
- .gitmodules
> Add in .gitmodules

- infrastructure/modules/api-management/output.tf
Adding output to the API Management module
Output required to create private DNS entries
---
> Adding output to module

- infrastructure/modules/api-management/main.tf
- infrastructure/modules/key-vault/main.tf
- infrastructure/modules/lets-encrypt-certificate/variables.tf
Adding Public IP address to the APIM as it is required when deploy it in multiples zones
---
> Add public IP address to the template

- infrastructure/modules/api-management/variables.tf
Add variable to API Management template to set gateway custom domain.
---
> Add variable to API Management Module

- infrastructure/modules/api-management/main.tf
- infrastructure/modules/api-management/variables.tf
Add sign up variable to setup the development portal
---
> Add sign-up variable

- infrastructure/modules/api-management/main.tf
Amending resource placement
---
> fix: DTOSS-3407-APIM-resource-placement

- infrastructure/modules/app-service-plan/main.tf
- infrastructure/modules/app-service-plan/variables.tf
- infrastructure/modules/diagnostic-settings/variables.tf
- infrastructure/modules/function-app/main.tf
- infrastructure/modules/function-app/variables.tf
- infrastructure/modules/key-vault/main.tf
- infrastructure/modules/key-vault/variables.tf
- infrastructure/modules/lets-encrypt-certificate/variables.tf
- infrastructure/modules/log-analytics-workspace/main.tf
- infrastructure/modules/log-analytics-workspace/variables.tf
- infrastructure/modules/network-security-group/main.tf
- infrastructure/modules/network-security-group/variables.tf
- infrastructure/modules/sql-server/main.tf
- infrastructure/modules/subnet/main.tf
- infrastructure/modules/subnet/variables.tf
- infrastructure/modules/vnet/main.tf
- infrastructure/modules/vnet/variables.tf
Merging deployed code for the diagnostic settings for resources.
---
> feat: dtoss 5205 diagnostic setting rollout

- infrastructure/modules/log-analytics-workspace/main.tf
- infrastructure/modules/log-analytics-workspace/variables.tf
Fixes for Diagnostics Settings across Hub, Audit and the Templates repo.
---
> feat: DTOS 5205 Fixes for Diagnostics Settings config

- infrastructure/modules/event-hub/main.tf
- infrastructure/modules/event-hub/output.tf
- infrastructure/modules/event-hub/variables.tf
- infrastructure/modules/key-vault/main.tf
- infrastructure/modules/log-analytics-data-export-rule/main.tf
- infrastructure/modules/log-analytics-data-export-rule/variables.tf
- infrastructure/modules/log-analytics-workspace/main.tf
- infrastructure/modules/log-analytics-workspace/output.tf
- infrastructure/modules/shared-config/output.tf
New module for Azure Even Hubs
---
> feat: DTOSS-5996: New Event Hub Module

- infrastructure/modules/sql-server/database.tf
- infrastructure/modules/sql-server/main.tf
- infrastructure/modules/sql-server/variables.tf
Configuration to change the redundancy option to 'Local', for DB backup storage
---
> feat: dtoss 0000 local backup storage option

- scripts/deployments/get-docker-names.sh
Case insensitive regex was not working. Changed approach to squash the string to be compared to lower case first using `${varname,,}`, then compare to a lower case version of the match string.
---
> Fix: regex match on Shared folder

- infrastructure/modules/lets-encrypt-certificate/scripts/certbot.sh
Azure Key Vault does not check certificate thumbprints when uploading, so a new version of a certificate will be created every time, even if the thumbprint has not changed. This change adds some logic around the upload to Key Vault, in the `lets-encrypt-certificate` Terraform module, to prevent the proliferation of duplicate certificate versions.
Successful run:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=12233&view=results
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase …
> fix: Skip uploading SSL certificates to Key Vault if thumbprint is unchanged

- infrastructure/modules/lets-encrypt-certificate/scripts/certbot.sh
Add a message during certificate upload to Key Vault to make the pipeline logging more self-explanatory.
---
> fix: improve verbosity of certificate upload to Key Vault

- .azuredevops/templates/steps/acr-import-retag.yaml
- .azuredevops/templates/steps/apply-database-changes.yaml
- .azuredevops/templates/steps/deploy-images-from-acr.yaml
- .azuredevops/templates/steps/run-post-deployment-tests.yaml
Add initial component templates for new end-to-end image management pipeline.
Removes manual processes involved with pushing images to new environments, and adds placeholder allowing automated test steps to be included in the pipeline.
---
> feat: dtoss-5599 image pipeline database changes template

- infrastructure/modules/postgresql-flexible/main.tf
- infrastructure/modules/postgresql-flexible/variables.tf
> feat: DTOS 00000 adding config for postgresql ds

- infrastructure/modules/function-app/main.tf
- infrastructure/modules/function-app/variables.tf
Adds `health_check_path` and `health_check_eviction_time_in_min` vars to function app site config map. 
No defaults added as these are optional.
We would like to monitor function app health.
---
> Add function app healthcheck vars

- infrastructure/modules/storage/main.tf
- infrastructure/modules/storage/variables.tf
-Enable Soft Delete for Blob Storage 
-Configure a retention period of 7 days for deleted data, ensuring it aligns with organisational policies.
-Allow versioning to be configurable
To enable Soft Delete for all Azure Storage Accounts in all environments, so that accidental data loss is preventable and allow recovery of deleted data within the retention period of 7 days.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. …
> feat: DTOS 7140 enabling soft delete for storage accounts

- infrastructure/modules/api-management/main.tf
- infrastructure/modules/api-management/variables.tf
- infrastructure/modules/virtual-desktop/scaling-plan.tf
- Enabling diagnostics logging apim 
- Setting minimum api version to 2021-08-01.
- Changing the Off peak times for AVD scaling to 22:00
- 
---
> feat: dtos 7243 enabling diagnostics logging apim minimum api version

- infrastructure/modules/container-registry/main.tf
- infrastructure/modules/container-registry/variables.tf
- infrastructure/modules/event-grid-topic/main.tf
- infrastructure/modules/event-grid-topic/variables.tf
- infrastructure/modules/event-hub/main.tf
- infrastructure/modules/event-hub/variables.tf
- infrastructure/modules/function-app/main.tf
- infrastructure/modules/function-app/variables.tf
- infrastructure/modules/key-vault/main.tf
- infrastructure/modules/key-vault/variables.tf
- infrastructure/modules/postgresql-flexible/main.tf
- infrastructure/modules/postgresql-flexible/variables.tf
- infrastructure/modules/sql-server/database.tf
- infrastructure/modules/sql-server/main.tf
- infrastructure/modules/sql-server/variables.tf
- infrastructure/modules/storage/main.tf
- infrastructure/modules/storage/variables.tf
It should be possible to set a number of Azure environment features to be either enabled or disabled depending upon the requirements and purpose of the environment. However a couple of minor issues prevent some of these from working correctly and this PR fixes these. 
Will allow more flexible deployment of environments, particularly those that do not require private endpoints and full auditing capabilities, such as the Temporary Environments proposed by DTOSS-7048.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull …
> feat: dtoss 7360 fix optional Terraform features

- .azuredevops/templates/steps/tf_destroy.yaml
- .azuredevops/templates/steps/tf_plan.yaml
- infrastructure/modules/sql-server/main.tf
- infrastructure/modules/sql-server/rbac.tf
Further template updates required to provide the Temporary Environments functionality.
---
> feat: dtoss 7048 deploy temp environments - further updates post dtoss-7360

- .github/workflows/stage-3-build-images.yaml
Though this implicit project name seems to have worked adequately for the other projects, it seems to default to the repo name for the Participant Manager project which adds an unwanted `dtos-` prefix to all the created docker images.
We do not want there to be room for inference differences when we already provide a `project_name` input variable to this workflow template. Therefore this changes the docker compose command to explicitly use the provided project name.
Other changes to avoid expanding input variables inline in shell scripts (to mitigate globbing or word splitting shell injection attacks).
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable …
> fix: explicit rather than implicit docker project name

- infrastructure/modules/container-registry/main.tf
- infrastructure/modules/container-registry/variables.tf
- infrastructure/modules/sql-server/main.tf
Creating diagnostic settings for ACR
---
> feat: dtoss 7530 ds acr

- .azuredevops/templates/steps/run-post-deployment-tests.yaml
- .azuredevops/templates/steps/tf_destroy.yaml
Fixes for testing automation pipelines.
---
> fix: dtoss 3350 fix service connection

- infrastructure/modules/sql-server/database.tf
- infrastructure/modules/sql-server/variables.tf
Add Database Backup Retention Policies to Azure SQL.
---
> fix: dtoss-7699 Azure SQL Database Backup Retention Config

- scripts/deployments/get-docker-names.sh
For Docker image CI - this fix will track file changes that are deeper in a Function App or Web App folder structure. Until now all Function Apps have had a flat folder structure (apart from properties) so this defect had apparently not been noticed. This will also cope with quite different path depths per App Service.
It also fixes new cases emerging from a reorganisation of Participant Manager compose file.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that …
> fix: DTOSS-7756 track file changes in nested folders for image rebuilds

- scripts/deployments/get-docker-names.sh
Reverts NHSDigital/dtos-devops-templates#114
> Revert "fix: DTOSS-7756 track file changes in nested folders for image rebuilds"

- scripts/deployments/get-docker-names.sh
Fix JSON encoding of FUNC_NAMES
---
> fix: JSON encoding issue

- scripts/deployments/get-docker-names.sh
> Fix: Improve code comments: get-docker-names.sh

- .azuredevops/templates/resources/deploy-container-instance-sql-db-migration.yaml
- .azuredevops/templates/steps/apply-database-changes.yaml
New templates to allow an Azure Container Instance to be deployed running a Docker container that performs any outstanding database updates by way of an Entity Framework implementation within the project application code.
---
> feat: DTOSS3350: Database migration templates

- .azuredevops/templates/steps/apply-database-changes.yaml
Bugfix to PR-129 which was closed with a file update missing.
---
> feat: DTOSS-3350 pipeline database management

- infrastructure/modules/shared-config/output.tf
Super simple change, just add another name in the shared config section for managed-identity 
---
> DTOSS-7985: ManagedIdentify Client-Id to execute automated tests in NFT

- scripts/deployments/get-docker-names.sh
Cohort Manager has become large enough that developers cannot deploy the whole application in local containers locally. Consequently the Docker compose files have been segmented based on functional chunks, so that a subset of the application can be locally hosted. The parent compose file contains include references to the other files.
The CI `get-docker-names.sh` script has been modified to walk compose file includes automatically so that pipeline changes are no longer required as the compose files evolve. Only the parent compose file needs to be defined by the calling workflow.
Linked to this Cohort Manager PR:
https://github.com/NHSDigital/dtos-cohort-manager/pull/841
Verified nested includes are working.
See comment below for Cohort Manager test👇
---
To ensure the utmost …
> feat: CI - evaluate Docker compose file includes

- .azuredevops/templates/steps/apply-database-changes.yaml
- .azuredevops/templates/steps/deploy-images-from-acr.yaml
Implement Function App restarts and improve parameterisation of the templates used in end-to-end deployment of images.
removes the need to manually restart functions after image deployment and makes templates more reusable.
---
> feat: dtoss 3350 Improve reusability of image management pipeline templates

- infrastructure/modules/application-gateway/main.tf
- infrastructure/modules/lets-encrypt-certificate/scripts/certbot.sh
- infrastructure/modules/shared-config/output.tf
- infrastructure/modules/storage/main.tf
- infrastructure/modules/virtual-desktop/session-host.tf
A few fixes, to clear the way for DTOSS-8363 - Publishing the Participant Manager www site:
- Application Gateway fix to make the probe optional in a `backend_http_settings` block
- Pin Certbot to a known-good version while version 4.0.0 isn't working properly with library josepy 2.0.0
- Remove deprecated parameter from virtual machine in Virtual Desktop module
- Replace deprecated parameter in Storage Account module
Successfully deployed to non-live Hub:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=17103&view=results
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-b …
> Feat: DTOSS-8363 Fixes to publish Participant Manager www

- infrastructure/modules/function-app/main.tf
- infrastructure/modules/linux-web-app/main.tf
- infrastructure/modules/sql-server/database.tf
- infrastructure/modules/virtual-desktop/session-host.tf
Some previously optional parameters for Linux Function App and for Linux Web App are mandatory now, so default them where appropriate to avoid needing code changes where modules are consumed. The other changes are from `terraform fmt`.
---
> Fix: DTOSS-4537 Changes for azurerm provider 4.26

- .github/workflows/stage-3-build-images.yaml
- scripts/deployments/append-commit-hash.sh
This PR includes a change that will result in adding a new tag with the short commit hash to all the images, not only those that were rebuild in the latest workflow run. 
This is a first step to a new image management workflow, that will allow us to easily target a specific point in time of the environment.
---
> feat: DTOSS-8139 append commit hash tag to all images

- infrastructure/modules/app-service-plan/certificate.tf
- infrastructure/modules/app-service-plan/output.tf
- infrastructure/modules/app-service-plan/variables.tf
- infrastructure/modules/lets-encrypt-certificates/data.tf
- infrastructure/modules/lets-encrypt-certificates/output.tf
- infrastructure/modules/lets-encrypt-certificates/scripts/certbot.sh
This change automates App Service certificate bindings, including workarounds for non-working Key Vault Certificate references to elliptic curve certificates. The workaround is that certificates are also stored as pfx blobs in Key Vault Secret objects, which App Services may reference without issue.
Workaround was necessary after it was established that there was a technical issue with App Service elliptic curve cryptography support via Key Vault (Azure Support Request 2505010050001340).
- Successfully deployed to Participant Manager Dev:
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and …
> Fix: DTOSS-8363 App Service certificate bindings

- infrastructure/modules/lets-encrypt-certificates/README.md
- infrastructure/modules/linux-web-app/main.tf
- infrastructure/modules/linux-web-app/providers.tf
Fix provider warning in `linux-web-app` module.
---
> fix: Add named provider configuration alias

- infrastructure/modules/app-service-plan/tfdocs.md
- infrastructure/modules/container-app-environment/README.md
- infrastructure/modules/container-app-environment/main.tf
- infrastructure/modules/container-app-environment/output.tf
- infrastructure/modules/container-app-environment/providers.tf
- infrastructure/modules/container-app-environment/tfdocs.md
- infrastructure/modules/container-app-environment/variables.tf
- infrastructure/modules/container-app/README.md
- infrastructure/modules/container-app/data.tf
- infrastructure/modules/container-app/main.tf
- infrastructure/modules/container-app/output.tf
- infrastructure/modules/container-app/tfdocs.md
- infrastructure/modules/container-app/variables.tf
- infrastructure/modules/lets-encrypt-certificates/tfdocs.md
- infrastructure/modules/managed-identity/output.tf
- infrastructure/modules/managed-identity/tfdocs.md
- infrastructure/modules/private-dns-a-record/providers.tf
- Remove race condition in container app and key vault. The container app module was erroring when the key vault was not created yet. Separate reading secrets from the key vault creation to avoid the race condition.
- Enable zone redundancy
- Create DNS records in private zone
- Output web app URL
Deploying the application from scratch didn't work because of the dependency on key vault
Test with manage branch https://github.com/NHSDigital/manage-breast-screening/tree/DTOSS-8324-container-app-module
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other …
> [DTOSS-8589] Container app improvements

- .azuredevops/templates/steps/run-post-deployment-pw-tests.yaml
- .gitignore
- scripts/integrations/slack/SlackIntegrator.py
- scripts/integrations/slack/SlackMessages.py
- scripts/integrations/slack/SlackWebhookBot.py
Add new integration functionality to send test results to designated Slack webhook.
Testers require messaging notifications when various E2E or general smoke tests have completed. They want to be notified of the results without the reliance on navigating ADO.
---
> feat: dtoss 7388 integrate post deployment test results with slack

- README.md
- infrastructure/modules/acme-certificate/README.md
- infrastructure/modules/acme-certificate/tfdocs.md
- infrastructure/modules/lets-encrypt-certificates/README.md
- infrastructure/modules/load-balancer/tfdocs.md
Didn't realise I needed to manually link new module docs to the root README.md, and I had forgotten to add the markdown files.
---
> Fix: acme-certificate markdown docs

- infrastructure/modules/acme-certificate/README.md
Corrected a crucial error in the worked example, that would have completely spoiled the understanding of a complex topic - CNAME redirection of ACME DNS-01 challenges.
---
> Update acme-certificate module README.md

- .github/workflows/stage-3-build-images.yaml
A fix for reaching the `compose.yaml` files.
---
-  I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.
> fix: DTOSS-8936 manual image rebuild

- infrastructure/modules/container-app-environment/data.tf
- infrastructure/modules/container-app-environment/main.tf
- infrastructure/modules/container-app-environment/variables.tf
- infrastructure/modules/container-app/data.tf
- infrastructure/modules/container-app/main.tf
- infrastructure/modules/container-app/variables.tf
- infrastructure/modules/shared-config/output.tf
- infrastructure/modules/shared-config/variables.tf
Remove the resource group data source in the container-app and container-app-environment modules
Also update the shared config. Required for the manager-breast-screening deployment.
The data source was relying on the resource group existence and failing when building an environment from scratch
---
> [DTOSS-8589] Fix container app RG data source error

- infrastructure/modules/service-bus-subscription/README.md
- infrastructure/modules/service-bus-subscription/example/example.tfvars
- infrastructure/modules/service-bus-subscription/example/main.tf
- infrastructure/modules/service-bus-subscription/example/variables.tf
- infrastructure/modules/service-bus-subscription/main.tf
- infrastructure/modules/service-bus-subscription/tfdocs.md
- infrastructure/modules/service-bus-subscription/variables.tf
- infrastructure/modules/service-bus/output.tf
Added a new module that creates the Service Bus subscription. 
Has an example of how to call it included within the module. 
---
> DTOSS-9226: Create Permissions for Foundry Function App

- .github/workflows/stage-3-build-images.yaml
Updated docker build command for the image build process.
Old command:
```
docker compose -f ${COMPOSE_FILE//,/ -f } -p ${PROJECT_NAME} build --no-cache --pull ${function}
```
New command: 
```
docker compose -f ${COMPOSE_FILE//,/ -f } -p ${PROJECT_NAME} --profile "*" build --no-cache --pull ${function
```
---
> fix: updated docker build command for the image build process

- .azuredevops/templates/steps/azure_sql_scale.yaml
We require a method to scale Azure SQL databases via a pipeline run.
This allows databases to be scaled to meet expected Peak and Off Peak loads while optimising costs. 
---
> feat: DTOSS-8108 Azure SQL Scaling template

- scripts/azure/azure_bulk_load.py
@adamsheldon1  create a bulk load script for the service bus for load testing. We now have this running from the ADO pipeline. This script can be used across many projects therefore should live in the templates repo. 
---
> DTOSS-9224: New bulk load Azure Service Bus script added

- infrastructure/modules/storage/README.md
- infrastructure/modules/storage/container-immutability-policy.tf
- infrastructure/modules/storage/tfdocs.md
- infrastructure/modules/storage/variables.tf
Add Storage Container Immutability Policy as an option when creating new storage account containers.
This allows storage containers to be created whereby the contents of the container, and the container itself, cannot be deleted within the constraints of the supplied policy parameters. This is required for storage of e.g. long term database backups.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate …
> feat: DTOSS-9884 Add storage container immutability option

- scripts/integrations/slack/SlackIntegrator.py
Add markdown formatting option to SlackIntegrator so that formatted messages can be sent.
---
> fix: Add markdown formatting option to SlackIntegrator

- infrastructure/modules/container-app-environment/main.tf
- infrastructure/modules/container-app-environment/tfdocs.md
- infrastructure/modules/container-app-environment/variables.tf
- infrastructure/modules/managed-identity-roles/tfdocs.md
- infrastructure/modules/monitor-action-group/main.tf
- infrastructure/modules/monitor-action-group/tfdocs.md
- infrastructure/modules/monitor-action-group/variables.tf
- infrastructure/modules/role-definition/tfdocs.md
Amend the Container App Environment module so that we can use it with Azure Monitor diagnostics exports as this is in alignment with how logging is handled for other resources.
Make `location` an optional input in `monitor-action-group`  module as it is an unused parameter and can be removed once dependent projects have been updated.
These changes have been confirmed to bebackward-compatible with existing projects by running a test Plan in Cohort Manager using the main branch code for the project, and the new branch for the modules: 
[ADO Test build](https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=27886&view=logs&j=d8cb62c2-aff2-5e3d-2ee6-50c587ce9a37)
Improves and logging consistency across resource types.
---
To ensure the utmost confidentiality and protect …
> feat: dtoss-10697 Azure Monitor Alerts

- README.md
- infrastructure/modules/container-app/README.md
- infrastructure/modules/container-app/alerts.tf
- infrastructure/modules/container-app/variables.tf
- infrastructure/modules/postgresql-flexible/README.md
- infrastructure/modules/postgresql-flexible/alerts.tf
- infrastructure/modules/postgresql-flexible/variables.tf
This alert was very hard to test: - 
---
> replica restart alert
