NHSDigital/dtos-devops-templates

- .tool-versions
fix: update Terraform version
update Terraform version for linting in CI
---
> fix: update Terraform version

- infrastructure/modules/function-app/rbac.tf
- infrastructure/modules/key-vault/rbac.tf
- infrastructure/modules/key-vault/variables.tf
- infrastructure/modules/storage/rbac.tf
- infrastructure/modules/storage/variables.tf
The Key Vault module now optionally accepts a list of RBAC roles to assign to the Terraform Managed Identity - ensuring that it will be able to reference items stored within it in future.
This change also brings a simplification to the Storage module's RBAC roles input variable, so a fix needs applying to the other projects using it:
- Cohort Manager (tested in a branch [here](https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=7554&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11c) successful plan, changes to diagnostic settings are unrelated, from test deployments from another branch)
- Service Insights (change added to the work-in-progress branch)
- Communication Management (already implemented)
---
To ensure the utmost …
> feat: DTOSS-4810 Add optional RBAC role assignment to Key Vault module

- infrastructure/modules/function-app/rbac.tf
- infrastructure/modules/key-vault/rbac.tf
- infrastructure/modules/sql-server/rbac.tf
- infrastructure/modules/storage/rbac.tf
Fix for naming typo in references to subordinate RBAC Assignment module. These names are not referenced in any of the three project codebases. This misspelled name was only used by modules which call the RBAC module. The impact of the change will be that the RBAC assignments will be re-created when projects are re-deployed with this new version of the Terraform module templates.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive …
> fix: module name spelling in calls to subordinate RBAC Assignment module

- infrastructure/modules/private-dns-zone/main.tf
This had been mistakenly made conditional to apply only for privatelink zones but in fact it will always be needed.
---
> fix: Private DNS zone link

- infrastructure/modules/diagnostic-settings/main.tf
- infrastructure/modules/diagnostic-settings/variables.tf
- infrastructure/modules/key-vault/main.tf
- infrastructure/modules/key-vault/variables.tf
- infrastructure/modules/log-analytics-workspace/main.tf
- infrastructure/modules/postgresql-flexible/main.tf
- infrastructure/modules/shared-config/output.tf
- infrastructure/modules/storage/main.tf
- infrastructure/modules/storage/variables.tf
Fix to prevent recreation of resources by hard-coding the metrics category. 
infrastructure/modules/diagnostic-settings/main.tf:
New variable required: var.metric_enabled
infrastructure/modules/log-analytics-workspace/main.tf:
Reference to azurerm_log_analytics_workspace.log_analytics_workspace.id now required within the module resource. Please use the expression:
target_resource_id = azurerm_log_analytics_workspace.log_analytics_workspace.id
infrastructure/modules/storage/main.tf:
New variable required called: var.monitor_diagnostic_setting_storage_account_metrics
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable …
> fix: DTOS 5205 apply metrics fix to avoid recreation of resources

- .github/workflows/stage-3-build-images.yaml
- scripts/deployments/get-docker-names.sh
- Account for variability in shared code folder name (now case insensitive)
- Parameterise the Docker image tag (defaults to `development`, but can now be specified)
---
> fix: Better matching of shared code folder name in CI image build

- infrastructure/modules/container-registry/main.tf
- infrastructure/modules/container-registry/variables.tf
Although a variable existed to control public network access to ACR, it was not being used. Therefore until now all ACRs deployed were publicly accessible (the default behaviour), and would keep being made public each time the Terraform state was deployed.
Also added zone redundancy option (which unfortunately means this is disabled on all ACRs deployed to date). To remediate this requires a replacement of each ACR, so it's best tackled asap.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase …
> fix: ACR module, block public network access is no longer ignored

- .azuredevops/templates/steps/acr-import-retag.yaml
ACR image copying and re-tagging pipeline suitable for re-use by all projects. It can retag images in either Dev or Prod project ACRs, and migrate images between them. It preserves the PR and commit ref tags when migrating images.
One significant improvement here is the parallelism of the `az acr` jobs, which should result in a rapid pipeline execution, even for projects which have many Docker images. Furthermore there is no need for artifact storage nor multiple pipeline stages.
This script has a pre-requisite of a DNS A record for the Dev ACR existing in the Prod Hub `privatelink.azurecr.io` domain which must resolve to the public IP of the Dev ACR.
Example run, in Communication Management project:
https://dev.azure.com/nhse-dtos/dtos-communication-management/_build/results?buildId=10156 …
> feat: ACR image import and re-tag pipeline template, inc. Prod

- infrastructure/modules/postgresql-flexible/database.tf
- infrastructure/modules/postgresql-flexible/main.tf
- infrastructure/modules/postgresql-flexible/output.tf
- infrastructure/modules/postgresql-flexible/variables.tf
Adds optional password based auth to Postgresql module, creating a secure password and storing it Key Vault.
Succesful deployment: https://dev.azure.com/nhse-dtos/dtos-communication-management/_build/results?buildId=10698&view=results
---
> feat: automate Postgres password auth

- infrastructure/modules/virtual-desktop/session-host.tf
- infrastructure/modules/virtual-desktop/variables.tf
Allows virtual desktop session hosts to be built with either `source_image_reference` as before (for stock Azure OS images), or with `source_image_id`. The module code expects the relevant parameters to be defined in either of the two variable objects:
- `source_image_reference` or
- `source_image_from_gallery`
This allows the virtual desktops to be built from a golden image complete with the required application software, which will need to be updated.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the …
> Feat: Amend virtual-desktop module to support Azure Compute Gallery OS images

- infrastructure/modules/event-grid-subscription/main.tf
- infrastructure/modules/function-app/main.tf
- infrastructure/modules/function-app/variables.tf
Code change to enabling health checks for function apps when a Health probe path is added to the tfvars
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=13649&view=logs&j=c970d263-77bb-52d7-1861-5b2637d7126d&t=c970d263-77bb-52d7-1861-5b2637d7126d
---
> feat: dtoss 6910 enabling health checks for function apps

- scripts/deployments/get-docker-names.sh
CI workflow template: De-duplicate the list of Docker containers to build.
If changes have been made to multiple folder levels within the same function we need to ensure the function is represented only once in the final list to build. Previously these cases were not handled at all hence wasn't an issue until now.
Previously each changed folder was checked to see if it precisely matched the root folder of each function. Changes in subfolders were missed altogether. Now each changed folder is checked for a regex match against the root folder of each function (so subfolders are correctly matched). However, changes to multiple levels will result in multiple matches for the same function - hence the need to ensure the final list is unique.
Some more script hardening as recommended by …
> fix: CI workflow template - ensure list of containers to build has been de-duped

- .github/workflows/stage-3-build-images.yaml
```
with:
fetch-depth: 2
```
The above additional parameter for the Git checkout was applied to the wrong repo (the templates repo, and not to the default repo checkout). Consequently the Docker container builds after merging a PR were failing from the 17th March when compromised GitHub Action `tj-actions/changed-files` was remove, until now.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your …
> fix: Bug in checkout comparison logic

- infrastructure/modules/virtual-desktop/session-host.tf
Azure Policy requires VMs to have a specific tag for some reason, otherwise their creation is denied.
Deployed to Dev Hub:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=16440&view=results
---
> fix: DTOSS-7964 VM tagging for Azure Policy requirement

- .github/workflows/stage-3-build-images.yaml
I have made some changes to the way the stage-3-building-images.yaml script works, this is to allow it to work in private / internal repos. This allows it to work with the repo jira-slack-interface repo. However, I also tested this out on the dtos-service-insights repo (below) to ensure it did not break on public repos. 
https://github.com/NHSDigital/dtos-service-insights/actions/runs/14034610622/job/39289670847
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR …
> Feat/dtoss 7894 create GitHub workflow for python application and acr push

- infrastructure/modules/virtual-desktop/session-host.tf
- infrastructure/modules/virtual-desktop/variables.tf
Within the Virtual Desktop module, virtual machine OS images can now be specified in three ways:
1. Source Image Reference (public images)
2. Source Image Gallery Reference (local private images)
3. Source Image ID (allows images in remote subscriptions, as long as managed identity has access)
This removes the need to copy the AVD image to a local compute gallery when updating from Dev to Prod. Azure makes that process very difficult, so this change greatly simplifies rolling out updates to the Azure Virtual Desktop image.
Deployed to Prod Hub in order to refresh the AVD hosts to an updated image:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=16630&view=results
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT …
> feat: DTOSS-7970 Allow specifying the AVD OS source_image_id directly

- infrastructure/modules/postgresql-flexible/output.tf
Make this Terraform module output conditional on `var.password_auth_enabled`.
Prevents the module from failing to deploy if we select Entra ID authentication only.
---
> fix: Postgres admin pwd Key Vault id is conditional

- infrastructure/modules/function-app/variables.tf
`storage_account_access_key` in Function App module is now optional
This allows us to use the Function App managed identity for storage account access. It is an optional parameter after all:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app
---
> Fix: storage_account_access_key in Function App module is now optional

- infrastructure/.gitignore
- infrastructure/modules/monitor-action-group/examples/example.tfvars
- infrastructure/modules/monitor-action-group/examples/main.tf
- infrastructure/modules/monitor-action-group/examples/variables.tf
- infrastructure/modules/monitor-action-group/main.tf
- infrastructure/modules/monitor-action-group/variables.tf
- infrastructure/modules/shared-config/output.tf
AB#DTOSS-8458
A Terraform module to provision `azurerm_monitor_action_group` resources, so we can standardise and streamline the creation of Azure Monitor Action Groups across our environments.
The module should support the following features:
- Setting the short name and full name of the action group.
- Adding various receiver types (email, SMS, webhook, etc.).
- Create an examples/ folder with a working example that demonstrates how to use the module, including:
Example variable values.
How to reference the module from an environment configuration.
Expected output.
https://dev.azure.com/nhse-dtos/dtos-service-insights/_build/results?buildId=17468&view=logs&j=ced2749f-787a-529b-d064-72b5c61df22f&t=a8ef944f-7917-542a-f805-14b39eb0c11c …
> feat: DTOSS-8458: Create a terraform module for azure action group

- infrastructure/modules/app-insights/output.tf
- infrastructure/modules/function-app/entra_id_group.tf
- infrastructure/modules/function-app/variables.tf
- infrastructure/modules/linux-web-app/entra_id_group.tf
- infrastructure/modules/linux-web-app/variables.tf
- infrastructure/modules/sql-server/main.tf
1. Adds `name` and `resource_group_name` outputs to Application Insights module.
2. Adds optional Entra ID group memberships for App Services (Function App, Web App).
Neither of these changes is impactful to existing code with module dependencies.
1. Will allow direct resource references between App Services in `tf-core` Terraform state, and Application Insights in`tf-audit` Terraform state. Allows the removal of some parameterisation from tfvars for stronger coupling.
2. Will allow replacement of individual RBAC roles per App Service with RBAC roles assigned via group memberships. Will greatly reduce Terraform deployment times for Cohort Manager (many Function Apps), but will need admin rights over an Organization Unit within Entra ID which is a request pending with CCOE team.
- …
> Fix: Add outputs to Application Insights module, optional Entra ID group memberships for App Services

- infrastructure/modules/monitor-action-group/examples/example.tfvars
- infrastructure/modules/monitor-action-group/examples/main.tf
- infrastructure/modules/monitor-action-group/examples/variables.tf
- infrastructure/modules/monitor-action-group/main.tf
- infrastructure/modules/monitor-action-group/variables.tf
- infrastructure/modules/service-bus/example/example.tfvars
- infrastructure/modules/service-bus/example/main.tf
- infrastructure/modules/service-bus/example/variables.tf
- infrastructure/modules/service-bus/main.tf
- infrastructure/modules/service-bus/variables.tf
Been working with Michael Justus to create a module for Azure service bus namespace and topics. 
We have also included detailed examples of how to call this too. 
This has been deployed here: -
https://dev.azure.com/nhse-dtos/dtos-service-insights/_build/results?buildId=17741&view=results
This module can deploy: -
Azure service bus namespaces and Azure service bus topics.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. …
> DTOSS-8565: Create a Terraform module for Azure Service Bus

- .github/workflows/stage-3-build-images.yaml
Because first this change was supposed to be a part of the existing `build-and-push` job, and just later it evolved into a separate job, it was missing the templates repo checkout jobs.
---
> fix: missing script file while running the append commit hash job

- infrastructure/modules/lets-encrypt-certificates/README.md
- infrastructure/modules/lets-encrypt-certificates/data.tf
- infrastructure/modules/lets-encrypt-certificates/output.tf
Add a markdown documentation page, and simplify outputs from LetsEncrypt Certificates module.
- Deployed to Hub Dev:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=18100&view=results
- Deployed to Hub Prod:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=18101&view=results
Linked to:
- https://github.com/NHSDigital/dtos-hub/pull/85
We don't really need the full details of the pfx blob as its own object (`id`, `location`, `name`, `naming_key`, `subject`, `versionless_id`). This is because when we are consuming this pfx, we need to access the Key Vault Secret resource's `value` property, and to do that we need to bind it using a data query. For that we only need to know the secret name, and which Key Vault contains it. Consequently we might as well just add …
> fix: DTOSS-8939 Document LetsEncrypt Certificates module and simplify outputs

- README.md
- infrastructure/modules/acme-certificate/main.tf
- infrastructure/modules/acme-certificate/output.tf
- infrastructure/modules/acme-certificate/providers.tf
- infrastructure/modules/acme-certificate/variables.tf
- infrastructure/modules/api-management/main.tf
- infrastructure/modules/api-management/tfdocs.md
- infrastructure/modules/api-management/variables.tf
- infrastructure/modules/app-service-plan/certificate.tf
- infrastructure/modules/app-service-plan/tfdocs.md
- infrastructure/modules/app-service-plan/variables.tf
- infrastructure/modules/application-gateway/main.tf
- infrastructure/modules/application-gateway/tfdocs.md
- infrastructure/modules/application-gateway/variables.tf
- infrastructure/modules/container-app-environment/output.tf
- infrastructure/modules/container-app-environment/providers.tf
- infrastructure/modules/container-app-environment/variables.tf
- infrastructure/modules/container-app/output.tf
- infrastructure/modules/lets-encrypt-certificates/README.md
- infrastructure/modules/lets-encrypt-certificates/main.tf
- infrastructure/modules/lets-encrypt-certificates/tfdocs.md
- infrastructure/modules/lets-encrypt-certificates/variables.tf
- infrastructure/modules/linux-web-app/providers.tf
- infrastructure/modules/shared-config/output.tf
- infrastructure/modules/virtual-desktop/main.tf
A new Terraform module for ACME Certificate, to replace the unconventional Let's Encrypt Certificates module.
➕ Underpinned by [certbot](https://github.com/certbot/certbot).
➕ Very reliable advanced certificate/DNS challenge automation.
➖ Had to use null resource, so although idempotent it was not truly Terrform stateful.
➕ Very simple module inputs.
➖ Implicit DNS challenge behaviour.
➖ Extensive custom code, implying a maintenance and comprehension overhead.
➖ Serial certificate processing.
➕ Underpinned by [lego](https://github.com/go-acme/lego).
➖ Well maintained, but lego azuredns DNS challenge has more constraints and corner cases than certbot - which must be handled: mandatory leaf zone NS record checks, which then require CNAME redirects for DNS Challenge, which in turn require a …
> feat: DTOSS-9083 ACME certificate module

- infrastructure/modules/acme-certificate/README.md
- infrastructure/modules/acme-certificate/main.tf
- infrastructure/modules/acme-certificate/tfdocs.md
- infrastructure/modules/acme-certificate/variables.tf
ACME Certificate module improvements:
- Refactored and considerably simplified DNS record name string manipulations.
- Preserved full subdomain depth of redirected domains, which avoids possible DNS-01 challenge collisions when using CNAME redirection. Previously `*.foo.example.com` and `*.bar.example.com` would both have collided with a challenge at `_acme-challenge.acme.example.com`. Now they would be challenged at `_acme-challenge.foo.acme.example.com`
and `_acme-challenge.bar.acme.example.com` respectively.
- Added tagging of azurerm resources.
- Successfully deployed to Hub Non-Live:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=18586&view=results
- Successfully deployed to Hub Live:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=18582&view=results …
> fix: ACME certificate module simplification & improvements

- infrastructure/modules/app-service-plan/main.tf
- infrastructure/modules/app-service-plan/variables.tf
Add optional zone balancing to App Services Plan module.
Ensured that this new parameter does not disrupt environments that do not set this parameter.
- Participant Manager deploy - no changes:
https://dev.azure.com/nhse-dtos/dtos-participant-manager/_build/results?buildId=18670&view=results
---
> feat: DTOSS-9032 app service plan zone balancing

- .github/actions/scan-vulnerabilities/action.yaml
- .github/workflows/stage-3-build.yaml
- infrastructure/modules/acme-certificate/README.md
- infrastructure/modules/container-app-environment/tfdocs.md
- infrastructure/modules/function-app/main.tf
- infrastructure/modules/function-app/tfdocs.md
- infrastructure/modules/function-app/variables.tf
- infrastructure/modules/service-bus-subscription/tfdocs.md
- infrastructure/modules/service-bus/tfdocs.md
- infrastructure/modules/storage/main.tf
- infrastructure/modules/storage/tfdocs.md
- infrastructure/modules/storage/variables.tf
- scripts/deployments/get-docker-names.sh
Several module enhancements required for the Service Layer infrastructure deployment:
- **Function App** module no longer requires a dedicated User Managed Identity for container retrieval from ACR (to support GitHub Container Registry).
- **Function App** resource now ignores all tags - can't be selective here unfortunately - to prevent Terraform removing on every plan the `hidden-link:` tagging created automatically by AzureRM (e.g. for Application Insights linkage).
- **Storage Account** module can now create Storage Queues as required.
Other minor changes:
- Small update to **ACME Certificate** module documentation.
- Regenerated all terraform-docs automatic documentation for the modules, which has captured some additional drift.
- Cosmetic fix to the output of `get-docker-names.sh` …
> feat: Terraform module changes for Service Layer infra

- infrastructure/modules/container-app/main.tf
Remove the null values from the list. They happen when not all identities are present.
It was causing error in the manage breast screening pipeline
> [DTOS-9339] Fix identities error in container app module

- .github/workflows/stage-3-build-images.yaml
Don't run the append hash job if the full rebuild was triggered
---
> fix: don't run the append hash job if the full rebuild was triggered

- infrastructure/modules/dns-a-record/variables.tf
- infrastructure/modules/private-dns-a-record/variables.tf
The previous regular expression were too restrictive. Updates:
- Allow . in the body to separate subdomains
- Allow * at the start for wildcard domains
- Use [:alnum:] for readability
- Allow _ in public records
Tested with manage breast screening private records
Failure in manage breast screening after https://github.com/NHSDigital/dtos-devops-templates/pull/144
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We …
> [DTOSS-9700] Update DNS record validation

- infrastructure/modules/container-app-environment/tfdocs.md
- infrastructure/modules/container-app-environment/variables.tf
The caller does not have to specify the value and the individual default values in the object are used
Tested successfully with Manage breast screening
Error in Manage breast screening where workload_profile is not set:
```
│ Error: Missing required argument
│
│   on main.tf line 57, in module "container-app-environment":
│   57: module "container-app-environment" {
│
│ The argument "workload_profile" is required, but no definition was found.
```
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the …
> [DTOSS-9699] Set default value for workload_profile

- infrastructure/modules/event-grid-subscription/variables.tf
- infrastructure/modules/event-grid-topic/variables.tf
- infrastructure/modules/firewall-policy/variables.tf
- infrastructure/modules/firewall/variables.tf
Fix some errors in a recent change to validate more Terraform input variables.
Hub non-live now plans ok:
https://dev.azure.com/nhse-dtos/dtos-hub/_build/results?buildId=19958&view=results
---
> fix: Terraform variable validation

- infrastructure/modules/container-app/main.tf
- infrastructure/modules/container-app/tfdocs.md
- infrastructure/modules/container-app/variables.tf
At the moment it is only required when using HTTP authentication. Remove the dependency to make deployment faster.
Improve review apps deployment time on Manage BS
Tested successfully in https://github.com/NHSDigital/dtos-manage-breast-screening/pull/373
---
> [DTOS-10841] Make infra key vault optional in container apps

- infrastructure/modules/container-app-environment/main.tf
- infrastructure/modules/container-app-environment/variables.tf
In order to be able to deploy multiple Container App Environments in the same subscription, we need to have a way of creating a different `custom_infra_rg_name` value per the instance of the CAE.
This PR enables that possibility by implementing the `custom_infra_rg_name` variable. If implemented on the client side, the module will use it during the deployment.
If it's not being parsed by the client repository (as it is right now), it will use the current `"${var.resource_group_name}-cae-infra"` option by default (**no breaking change**).
The example of a plan **without** the `custom_infra_rg_name` specified by the client repository (no changes):
https://dev.azure.com/nhse-dtos/dtos-cohort-manager/_build/results?buildId=27345&view=logs&j=2e61fdd4-29ab-51b4-3516-655c0df6fcf2&t=430e7011-249c- …
> fix: DTOSS-10994 Deploy the CAE with a different custom_infra_rg_name value per CAE instance

- infrastructure/modules/postgresql-flexible/variables.tf
Seeing some TF deploy errors on Manage relating to devops templates changes, is there a corresponding Manage PR? We're missing postgres values for enable_monitoring and action_group_id and these don't have defaults
---
> DTOSS-11103: Put defaults on postgres variables
